export const URLS = {
    getMe: "/api/auth/get-me",
    signIn: "/api/auth/sign-in",
    get_certificate: "/api/certificate/get-cert",
    get_certificate_by_student_id: "/api/certificate/get",
    exercise_add: "/api/exercise/add",
    exercise_list: "/api/exercise/get",
    exercise_get_by_id: "/api/exercise/get-by",
    exercise_get_by_student_id: "/api/exercise/get-by-student-id",
    exercise_type_add: "/api/exercise-type/add",
    exercise_type_delete: "/api/exercise-type/delete",
    exercise_type_edit: "/api/exercise-type/edit",
    exercise_type_list: "/api/exercise-type/get",
    exercise_type_get_by_id: "/api/exercise-type/get-by",
    student_add: "/api/student/add",
    student_delete: "/api/student/delete",
    student_edit: "/api/student/edit",
    student_list: "/api/student/get",
    student_get_by_id: "/api/student/get-by",
    training_center_add: "/api/training-center/add",
    training_center_delete: "/api/training-center/delete",
    training_center_edit: "/api/training-center/edit",
    training_center_list: "/api/training-center/get",
    training_center_get_by_id: "/api/training-center/get-by",
};
